language: java
dist: trusty

sudo: false

addons:
  apt:
    packages:
      - tcl
      - tcllib
      - ruby

cache:
  - apt

before_script:
  - gem install --no-ri --no-rdoc cucumber

script:
  - gradle cucumber_tcl
